import type { ThemeId } from "@/data/types";

export interface ThemeConfig {
  id: ThemeId;
  name: string;
  preview: string; // accent color for preview dot
  vars: Record<string, string>;
}

export const themes: ThemeConfig[] = [
  {
    id: "noir",
    name: "Noir",
    preview: "#D4AF55",
    vars: {
      "--color-bg-primary": "#080807",
      "--color-bg-elevated": "#121110",
      "--color-bg-subtle": "#1A1918",
      "--color-bg-card": "#161514",
      "--color-border-default": "#222120",
      "--color-border-hover": "#333130",
      "--color-text-primary": "#F5F0E8",
      "--color-text-secondary": "#A8A29E",
      "--color-text-tertiary": "#78716C",
      "--color-text-accent": "#D4AF55",
      "--color-accent-gold": "#D4AF55",
      "--color-accent-gold-hover": "#E0BF6A",
      "--color-accent-gold-muted": "rgba(212, 175, 85, 0.08)",
      "--color-accent-gold-glow": "rgba(212, 175, 85, 0.2)",
      "--color-accent-gold-bright": "#F0D078",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    preview: "#60A5FA",
    vars: {
      "--color-bg-primary": "#06080D",
      "--color-bg-elevated": "#0D1117",
      "--color-bg-subtle": "#151B26",
      "--color-bg-card": "#111820",
      "--color-border-default": "#1C2433",
      "--color-border-hover": "#2A3548",
      "--color-text-primary": "#E6EDF6",
      "--color-text-secondary": "#8B9BB5",
      "--color-text-tertiary": "#5A6A85",
      "--color-text-accent": "#60A5FA",
      "--color-accent-gold": "#60A5FA",
      "--color-accent-gold-hover": "#7DB8FC",
      "--color-accent-gold-muted": "rgba(96, 165, 250, 0.08)",
      "--color-accent-gold-glow": "rgba(96, 165, 250, 0.2)",
      "--color-accent-gold-bright": "#93C5FD",
    },
  },
  {
    id: "ember",
    name: "Ember",
    preview: "#F97316",
    vars: {
      "--color-bg-primary": "#0A0806",
      "--color-bg-elevated": "#141008",
      "--color-bg-subtle": "#1C1610",
      "--color-bg-card": "#18120C",
      "--color-border-default": "#2A2016",
      "--color-border-hover": "#3A2E20",
      "--color-text-primary": "#F5EDE4",
      "--color-text-secondary": "#B5A08A",
      "--color-text-tertiary": "#7A6850",
      "--color-text-accent": "#F97316",
      "--color-accent-gold": "#F97316",
      "--color-accent-gold-hover": "#FB923C",
      "--color-accent-gold-muted": "rgba(249, 115, 22, 0.08)",
      "--color-accent-gold-glow": "rgba(249, 115, 22, 0.2)",
      "--color-accent-gold-bright": "#FDBA74",
    },
  },
  {
    id: "forest",
    name: "Forest",
    preview: "#34D399",
    vars: {
      "--color-bg-primary": "#060A08",
      "--color-bg-elevated": "#0C1210",
      "--color-bg-subtle": "#141C18",
      "--color-bg-card": "#101814",
      "--color-border-default": "#1A2620",
      "--color-border-hover": "#283830",
      "--color-text-primary": "#E8F5F0",
      "--color-text-secondary": "#8AAFA0",
      "--color-text-tertiary": "#5A7A6C",
      "--color-text-accent": "#34D399",
      "--color-accent-gold": "#34D399",
      "--color-accent-gold-hover": "#5EEAB5",
      "--color-accent-gold-muted": "rgba(52, 211, 153, 0.08)",
      "--color-accent-gold-glow": "rgba(52, 211, 153, 0.2)",
      "--color-accent-gold-bright": "#6EE7B7",
    },
  },
  {
    id: "royal",
    name: "Royal",
    preview: "#A78BFA",
    vars: {
      "--color-bg-primary": "#08060D",
      "--color-bg-elevated": "#100D18",
      "--color-bg-subtle": "#1A1524",
      "--color-bg-card": "#14101E",
      "--color-border-default": "#221C33",
      "--color-border-hover": "#332A4A",
      "--color-text-primary": "#EDE6F8",
      "--color-text-secondary": "#9B8FBB",
      "--color-text-tertiary": "#6A5A8A",
      "--color-text-accent": "#A78BFA",
      "--color-accent-gold": "#A78BFA",
      "--color-accent-gold-hover": "#B9A2FC",
      "--color-accent-gold-muted": "rgba(167, 139, 250, 0.08)",
      "--color-accent-gold-glow": "rgba(167, 139, 250, 0.2)",
      "--color-accent-gold-bright": "#C4B5FD",
    },
  },
  {
    id: "ivory",
    name: "Ivory",
    preview: "#92815A",
    vars: {
      "--color-bg-primary": "#F5F2ED",
      "--color-bg-elevated": "#FFFFFF",
      "--color-bg-subtle": "#EDE9E3",
      "--color-bg-card": "#FAFAF8",
      "--color-border-default": "#E0DBD4",
      "--color-border-hover": "#D0C9BF",
      "--color-text-primary": "#1A1816",
      "--color-text-secondary": "#6B6560",
      "--color-text-tertiary": "#9B9590",
      "--color-text-accent": "#92815A",
      "--color-accent-gold": "#92815A",
      "--color-accent-gold-hover": "#A5936A",
      "--color-accent-gold-muted": "rgba(146, 129, 90, 0.08)",
      "--color-accent-gold-glow": "rgba(146, 129, 90, 0.15)",
      "--color-accent-gold-bright": "#B8A578",
    },
  },
  {
    id: "monochrome",
    name: "Mono",
    preview: "#FFFFFF",
    vars: {
      "--color-bg-primary": "#000000",
      "--color-bg-elevated": "#0F0F0F",
      "--color-bg-subtle": "#1A1A1A",
      "--color-bg-card": "#141414",
      "--color-border-default": "#222222",
      "--color-border-hover": "#333333",
      "--color-text-primary": "#FFFFFF",
      "--color-text-secondary": "#999999",
      "--color-text-tertiary": "#666666",
      "--color-text-accent": "#FFFFFF",
      "--color-accent-gold": "#FFFFFF",
      "--color-accent-gold-hover": "#E0E0E0",
      "--color-accent-gold-muted": "rgba(255, 255, 255, 0.06)",
      "--color-accent-gold-glow": "rgba(255, 255, 255, 0.15)",
      "--color-accent-gold-bright": "#FFFFFF",
    },
  },
];

export function getTheme(id?: string): ThemeConfig {
  return themes.find((t) => t.id === id) ?? themes[0];
}
